= Solution Patterns: Event Driven API Management
:page-layout: home
:sectnums:
:sectlinks:
:doctype: book
:imagesdir: ../assets/images

This solution pattern showcases an architecture approach for building event-driven API Management that expands your API Management strategy beyond RESTful APIs into event-driven architecture.

Rather than the synchronous request-response pattern of RESTful APIs,event-driven APIs facilitate asynchronous communication with pub-sub pattern between the API provider and the API consumers, allowing the API consumer to subscribe to an API product by providing a webhook endpoint to receive events in real time without the need for polling the API server.

The solution leverages https://www.redhat.com/en/resources/application-foundations-datasheet[Red Hat Application Foundations^] components to build a scalable webhook delivery system. This system pushes internal events from your event broker (Kafka) to your API consumers, allowing you to manage events as an API product by applying API management practices to an event-driven API product.

*Contributors:* Abdelhamid Soliman

++++
 <br>
++++
[NOTE]
====
Solutions Patterns help you understand the art of the possible with Red Hat's portfolio, and not intended to be used as is for production environments. You are welcome use any part of this solution pattern for your own workloads.
====
[#use-cases]
== Use cases

Common use cases that can be address with this architecture are:

- Manage, secure, monitor, monetize and control event-driven APIs using traditional API Management practices.
- Enable to easily  consume third-party and internal consumer applications through the friendly HTTP protocol by hiding the complexity of internal event broker (kafka)
- Collaborate, document and self-service event-driven APIs through your developer portal.
- Increase innovation as app developers (internal/external developers, partners) can build  real-time reactive user interfaces and enable process automation based on internal business events in real time.

include::01-pattern.adoc[]
